version: 1.0.{build}
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
build:
  project: hexed.sln
  verbosity: minimal
artifacts:
  - path: $(PLATFORM)\$(CONFIGURATION)\hexed.exe
    name: hexed-deploy